-- Insert static data into SECURITIES table
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('AAPL', 'STOCK', NULL, NULL);
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('AAPL-JAN-2025-150-C', 'CALL', 150.00, '2028-01-15');
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('AAPL-JAN-2025-150-P', 'PUT', 100.00, '2028-06-30');
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('TSLA', 'STOCK', NULL, NULL);
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('TELSA-DEC-2020-400-P', 'PUT', 400.00, '2026-12-31');
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('TELSA-JUN-2028-600-C', 'CALL', 600.00, '2028-06-30');
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('GOOGL', 'STOCK', NULL, NULL);
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('MSFT_CALL_250', 'CALL', 250.00, '2023-12-31');
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('NFLX_PUT_450', 'PUT', 450.00, '2023-11-10');
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('AMZN', 'STOCK', NULL, NULL);
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('FB', 'STOCK', NULL, NULL);
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('TWTR_CALL_55', 'CALL', 55.00, '2024-05-15');
INSERT INTO SECURITIES (IDENTIFIER, TYPE, STRIKE, MATURITY) VALUES ('TWTR_PUT_35', 'PUT', 35.00, '2023-10-25');