DROP TABLE IF EXISTS SECURITIES;
CREATE TABLE SECURITIES
(
    ID        INT AUTO_INCREMENT  PRIMARY KEY,
    IDENTIFIER   VARCHAR(256) NOT NULL,
    TYPE ENUM('STOCK', 'CALL', 'PUT') NOT NULL,
    CURRENT DECIMAL(10, 2) DEFAULT NULL,
    STRIKE DECIMAL(10, 2) DEFAULT NULL,
    MATURITY DATE,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_SECURITES PRIMARY KEY (ID)
);