package com.itsz.portfolio.service.calculator

import kotlin.math.exp
import kotlin.math.ln
import kotlin.math.pow
import kotlin.math.sqrt

object BlackScholesUtil {

    const val INTEREST_RATE = 0.02
    const val SIGMA = 0.20

    // Cumulative normal distribution function generated by ChatGPT
    private fun cumulativeNormalDistribution(x: Double): Double {
        val b1 = 0.31938153
        val b2 = -0.356563782
        val b3 = 1.781477937
        val b4 = -1.821255978
        val b5 = 1.330274429
        val p = 0.2316419
        val c2 = 0.3989423

        return if (x >= 0.0) {
            val t = 1.0 / (1.0 + p * x)
            1.0 - c2 * exp(-x * x / 2.0) * t * (t * (t * (t * (t * b5 + b4) + b3) + b2) + b1)
        } else {
            val t = 1.0 / (1.0 - p * x)
            c2 * exp(-x * x / 2.0) * t * (t * (t * (t * (t * b5 + b4) + b3) + b2) + b1)
        }
    }

    private fun d1(S: Double, K: Double, T: Double): Double =
        (ln(S / K) + (INTEREST_RATE + 0.5 * SIGMA.pow(2)) * T) / (SIGMA * sqrt(T))

    fun calculateCallOptionPrice(S: Double, K: Double, T: Double): Double {
        val d1 = d1(S, K, T)
        val d2 = d1 - SIGMA * sqrt(T)
        return S * cumulativeNormalDistribution(d1) - K * exp(-INTEREST_RATE * T) * cumulativeNormalDistribution(d2)
    }

    fun calculatePutOptionPrice(S: Double, K: Double, T: Double): Double {
        val d1 = d1(S, K, T)
        val d2 = d1 - SIGMA * sqrt(T)
        return K * exp(-INTEREST_RATE * T) * cumulativeNormalDistribution(-d2) - S * cumulativeNormalDistribution(-d1)
    }
}
